### PR TITLE
Brighter grey colors

### PR DESCRIPTION
**Pull request by orellazri**
Brighter grey colors (for the game list), that look better in my opinion.

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Do you have a set of comparison screenshots?

**Comment by orellazri** [comment]
Old: http://i.imgur.com/fKpLmcB.png
New: http://i.imgur.com/IvYLadh.png

**Comment by FlaminSarge** [comment]
You have to keep in mind that this changes ALL instances of lightestGrey/etc., not just those for the text in the game list.

It may be better to specify a new color definition "lightestGreyText" or something for these to avoid changing styling on other things.

**Comment by DirtDiglett** [comment]
Yeah as @FlaminSarge mentioned, it's not specifically going to lighten the text and i'm not comfortable doing it globally. I'm denying this PR.

**Comment by thatkidluke** [comment]
thank you orellazi for you contribution, i understand that doing this globally would maybe pull to many unwanted strings, but this was my biggest issue with this excellent Skin. I would love to have them a bit brighter in some way. 

cheers

**Comment by FlaminSarge** [comment]
@orellazri submit a new pull request that adds new listLightestGrey and listLighterGrey color definitions and changes the places that use lightestGrey and lighterGrey for those particular text instances to use the new definitions.

If you have trouble finding those places, submit a bug and somebody will see what they can do. Make sure you include the color definition changes in the bug information. Having those screenshots isn't a bad idea either.

**Pull request closed without merging**
