### PR TITLE
Added Broadcast menu item, fixed some spelling errors

### PR DESCRIPTION
**Pull request by sebj**
Small pull request, title says it all I think. :)

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Where does the Broadcast menu item show up, again? D'you have a screenshot?
If it's this menu here, it seems like even without this change, I've got the Broadcast entry.
http://i.imgur.com/quL3Qct.png

**Comment by Zerathos** [comment]
If you view the commit you can see the file modified is steam.menu. That's the top left one with the Steam icon you click, not the hover drop-down.

**Comment by DirtDiglett** [comment]
Thanks for the fixes!

**Comment by FlaminSarge** [comment]
It's probably important to mention that that change is for OSX rather than all OS's.

**Comment by sebj** [comment]
I created the pull request and then went offline (slept), so I didn't see the comments here. Sorry, I should've been more specific about the menu change. Thanks for merging though :)

**Pull request merged**
