### PR TITLE
Fix truncated buttons, game invite, search bar

### PR DESCRIPTION
**Pull request by CaptainMagma**
This fixes the truncated close and minimize buttons on a few panels, the Choose Friend to invite panel in Steam Overlay, and the search bar in Steam Small Mode. Because I don't use Mac, none of the changes I have made will be applied to the Mac version.

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Does the change to left.tga affect all the other search bars? Wouldn't that be an issue? And is the inclusion of a new steamscheme.res for the truncated buttons?

And d'you have any screenshots of the result of this PR?

**Comment by DirtDiglett** [comment]
I'll have to test a few things with these changes before commiting them, so will pull it in if all goes well there. Thanks for providing the fixes!

**Comment by CaptainMagma** [comment]
@FlaminSarge The left.tga file is used for the other search bars and so they would be affected, but not in a negative way. The image is the same size. All I did was erase around the left side of it to make its background transparent to match right.tga. Yes, the inclusion of the steamscheme.res file is to fix pretty much every panel that had truncated buttons. For your third question, the change in the steam.styles that adds the "FriendsList" field is to fix a minor issue for a game invite panel used in some games such as Borderlands where you have a button you click that opens your steam overlay to allow you to invite players to your game. I've posted the screenshots in the steam discussion under the name Shazam if you'd like to see the fix for the truncated buttons and the game invite panel.

**Comment by CaptainMagma** [comment]
@DirtDiglett Now that I think about it, I probably should have added the "FriendsList" field to the friendsandchat.styles file instead to keep it organized.

**Comment by FlaminSarge** [comment]
@CaptainMagma ah, I noticed that the transparent bit didn't seem to reach all the way to the corners when I looked, which is why I was concerned.

**Comment by DirtDiglett** [comment]
After testing all seems to be usable still so i've merged this in. I want to thank you a lot for this one, I was struggling with the close button being glitched and completely forgot about the old steamscheme.res file which fixed it up! MANY THANKS

**Comment by CaptainMagma** [comment]
It's no problem. I'm a fan of the skin and am happy to help, so thank you and everyone else involved for the skin.

**Comment by CaptainMagma** [comment]
By the way, I think issues #131 and #140 should be fixed as well with the addition of the steamcheme.res.

**Comment by FlaminSarge** [comment]
Are you going to move the FriendsList stuff into that other include?

**Pull request merged**
