### PR TITLE
Added the "Check for Steam Client Updates" item to the menu.

### PR DESCRIPTION
**Pull request by KamranMackey**

### CODE REVIEW

**Comment by alvr** [comment]
That option where removed on purpose. #153

**Comment by FlaminSarge** [comment]
I think the "Restart Steam" option covers the features requested here, since restarting Steam forces it to check for updates (but restarts it very quickly if no updates are present).

**Comment by KamranMackey** [comment]
No it doesn't. It restarts the damn client, which I don't want to have to
do when checking for Steam updates.

On Thu, May 28, 2015 at 4:50 AM, FlaminSarge <notifications@github.com>
wrote:

> I think the "Restart Steam" option covers the features requested here,
> since restarting Steam forces it to check for updates (but restarts it very
> quickly if no updates are present).
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/DirtDiglett/Pressure-for-Steam/pull/363#issuecomment-106270198>
> .
>



-- 
- Kamran Mackey

**Comment by KamranMackey** [comment]
@DirtDiglett Why the heck would you remove something that's literally in every other skin and is useful? I find that just ridiculous.

**Comment by Connor37** [comment]
@KamranMackey I don't think they will add this feature. It is redundant, Steam will eventually update to the latest version when you leave it open.

**Comment by Zerathos** [comment]
@KamranMackey It's not in every other skin, I know because when I used Metro I had to maintain my own menu file to add it back (among other changes). It's not difficult and if it's a feature you find useful you ought to just add it yourself.

**Comment by Js41637** [comment]
Yeah it's defiantly not needed in the menu, because everything is under one menu things that aren't needed shouldn't be in there. Just restart Steam to update, it's literally the same except one downloads in Steam the other downloads before Steam launches. Steam can still even download the update in the background if Steam is open long enough.

**Comment by Zerathos** [comment]
It's not really the same thing. Sometimes Steam is flaky and doesn't update on restart, so forcing it is a nice perk, you get a changelog right there, and if your client already happened to pick up the update and you missed it you don't waste time restarting. Sure, minor benefits, but completely understandable why people want it in the menu. Again, it's not difficult to do it yourself so I'd urge anyone who finds the feature useful to do so rather than fighting for it.

**Comment by DirtDiglett** [comment]
Steam checks periodically while running for updates, it checks for updates when starting and restarting as well. There is no instance where the button itself is necessary as it's completely redundant. Steam needs to restart to install an update anyway so there's no scenario that the button is necessary other than to jerk off to by clicking it.


> No it doesn't. It restarts the damn client, which I don't want to have to
do when checking for Steam updates.

You need to restart to install an update anyway, your argument is invalid.

> @DirtDiglett Why the heck would you remove something that's literally in every other skin, including the default skin and is useful? I find that just ridiculous.

Because it is redundant. As another example: You have a car with 6 wheels, two of those wheels don't actually do anything that the 4 other wheels is already doing, these wheels are redundant so why waste the space that they exist in by keeping them there? Just because other skins keep the option doesn't mean I will. If another skin uses bright pink as its main color would I? No.

If you want it in the menu so badly just add the option to the file yourself and solve your own problem.

**Comment by KamranMackey** [comment]
@DirtDiglett It is not redundant...If it was it wouldn't be in any skin. Just add the damn thing to the menu.

**Comment by alvr** [comment]
@KamranMackey If you want it, use your custom menu. Probably the menu will be only updated to change the version number of Pressure.

**Pull request closed without merging**
