### PR TITLE
[Beta] Add phonereminderbar

### PR DESCRIPTION
**Pull request by Js41637**
Adds the phone reminder bar. This seems to overwrite the email reminder bar so i'm not sure if valve thought this through.

image

### CODE REVIEW

**Comment by Js41637** [comment]
Should also be noted that at the moment this reminder bar will re-appear every time Steam Restarts (unless you add a phone number I hope) so I dunno if adding it or making it that annoying is a good idea.

**Comment by Js41637** [comment]
Actually it might just be a bug. http://steamcommunity.com/groups/SteamClientBeta/discussions/0/523897653293503969/

**Comment by iraturus** [comment]
I tried it adding a phone number and the reminder bar is still appearing after restarting steam. So Valve didn't really think that through it seems.

**Comment by Js41637** [comment]
Typical Valve, I guess it is safe to assume then that the reminder is only meant to be shown once and not on every restart.

**Comment by Js41637** [comment]
Apparently Valve fixed the message box showing up on every startup.

**Comment by Wiggin38** [comment]
It's back again for me for whatever reason.

**Comment by bykidi** [comment]
Valve...

**Pull request merged**
