### PR TITLE
Update Beta Branch to Current Master + Fixes

### PR DESCRIPTION
**Pull request by FlamingFox911**
- Linux/OSX vs Windows Overlay Options Formatting. #450 (Temporary Solution)
- Formatted options for Advanced Client and Host Submenus in In-Home Streaming
- Formatted options for Desktop Game Theatre. #454 & #455

### CODE REVIEW

**Comment by FlamingFox911** [comment]
Apologies for the constant creations and deletions of Pull Requests. Took a while to get the right one to be created.

**Comment by bykidi** [comment]
someone merge this already

**Comment by FlamingFox911** [comment]
The Master Steam Client has been updated (March 31st) to incorporate all the changes here in the Beta Steam Client. After this gets merged, it is highly recommended to **sync** (not merge) this with the Master branch.

**Comment by bykidi** [comment]
Like, for real...

**Comment by bykidi** [comment]
Year 2022... PR still not merged.

**Comment by ErikHumphrey** [comment]
.

**Comment by KIPdeKIP** [comment]
Bump.

@DirtDiglett @FlamingFox911 Any update on this?

**Comment by FlamingFox911** [comment]
I am unsure, @KIPdeKIP. So far the only activity that has happened here has been from the Pull Request I have made. I am considering sending a PM, but you already @ mentioned him just now so he may see it.

Now to explain the lack of activity here, I'll direct you to a quote from one of his [Steam Announcements](http://steamcommunity.com/groups/pressureskin#announcements/detail/857178621344010301):

> Dark Theme
> 170+ comments, reddit messages, and steam messages... I get it, you want a dark theme, you don't like the light theme.
> 
> I never intended Pressure² to be anything but what it is now, and I'm not promising a dark theme for it nor am I taking that option off the table, I need to think on it further. What I will promise is that "Pressure Classic" is going to begin development now, and it will be dark, it will be a good blend of Pressure1 and Pressure² - and this one is for you guys, I personally won't ever use it, but I'm going to do it for you.
> 
> Pressure Classic
> Pressure Classic will replace the original Pressure when it's complete, and this is what those of you who are after a dark theme will want. This will be developed openly so you can provide feedback on it as it is being developed.

**Comment by bykidi** [comment]
Wow, that was fast. Thanks for fixed on that page :+1:

**Comment by Js41637** [comment]
lol

**Comment by FlamingFox911** [comment]
I have opened an issue tracker on my fork, in case people want to post there for some odd reason.
I have also made a Wiki on my fork, explaining the current happenings with the Pressure skins. If I have made a mistake, let me know.
Cheers.

**Comment by Js41637** [comment]
Nice work on the fixes and keeping it updated I don't have access to this repo so unfortunately there is nothing I can do.

**Comment by FlamingFox911** [comment]
I just added you as a collaborator to the fork. Learning more about Github everytime.

**Comment by Js41637** [comment]
I meant this repo as in this repo lol but, I initially did fix a bunch of things but I wasn't able to commit them here but you've fixed them as well now so it's all good.

**Comment by bykidi** [comment]
@DirtDiglett bump

**Comment by bykidi** [comment]
happy holidays everyone :)

**Pull request merged**
