### PR TITLE
Fix Steam Broadcasting invite bars

### LINKED ISSUE #157: Request to watch broadcast broken
http://i.gyazo.com/053103d006341bb18eeb191465a9f0cb.png

If someone requests to watch my broadcast the window is too small to accept.

### PR DESCRIPTION
**Pull request by FlaminSarge**
Broadcast Invitation Notifications probably also need some kind of fix.
Fixes #157 

Known issue: text "{User} has invited you to watch their broadcast" is cut off (well, it trails off into '...') for small chat windows for users with longer names.

### CODE REVIEW

**Comment by FlaminSarge** [comment]
Here's the known issue:
http://i.imgur.com/1hC7H9k.png

**Comment by CorruptComputer** [comment]
Can't you split the text into 2 lines? Even if the name doesn't make it trail off.

**Comment by FlaminSarge** [comment]
I'm trying to see if I can.

**Comment by FlaminSarge** [comment]
That is actually an issue with Steam itself...
http://puu.sh/eLKW3/a5c6927a4a.png

**Pull request merged**
