### PR TITLE
Steam Client Beta Update (2017-03-29)

### LINKED ISSUE #474: Problem with Advanced Host Options Dialog in Pressure 1.0.8
advanced-host

This dialog is located under Settings > In-Home Streaming  > Advanced Host Options

### PR DESCRIPTION
**Pull request by FlamingFox911**
Resolves #474

### CODE REVIEW

**Comment by Js41637** [comment]
You created your pull to the wrong branch but is this a beta change? Steam is very vague about actual changes in their updates.

**Comment by Js41637** [comment]
Note I moved the commit over to the beta branch and fixed master.

**Comment by FlamingFox911** [comment]
Ah right, my bad. Did that late at night. Was my second attempt through. Thanks for noticing and fixing.

**Comment by Js41637** [comment]
yeah it's fine, it's easy to do, don't know why Github doesn't let you change the branch for pull requests after they've been made.

**Pull request merged**
